### ISSUE TITLE
Error al solaparse mensajes.

### ISSUE THREAD

**Issue by alegamdev** [EGC-G2-Trabajo-1718/Cabina-Telegram#10]
**Prioridad:** Alta
**Descripción:** Hay un solapamiento en el bot al ejecutar el método /exit, se solapa con un mensaje del método /votar.

**Comment by AlbertoBujMun** [comment]
Se ha encontrado el error. Añadir que solo se responda al mensaje cuando sea respuesta a uno determinado.

**Comment by daniglper** [comment]
Problema solucionado en commit ce989c3934c939e6e63b15a3313b87bcd043681d
