### ISSUE TITLE
Config: Configuración de travis.yml

### ISSUE THREAD

**Issue by AlbertoBujMun** [EGC-G2-Trabajo-1718/Cabina-Telegram#11]
Hay que configurar correctamente los campos del archivo Travis.yml para que se realice la integración con docker de manera correcta.

**Comment by vicrosa25** [comment]
Arreglado. El problema no estaba en el archivo travis.yml sino en la versión del  compilador de maven que se estaba utilizando. No leía las expresiones lambdas. En el pom.xml del projecto he establecido una versión más actual. Ya compila en travis y no da error.
