### ISSUE TITLE
Métodos auxiliares en holaBot

### ISSUE THREAD

**Issue by Jultrocor** [EGC-G2-Trabajo-1718/Cabina-Telegram#14]
**Prioridad:** Baja.
**Descripción:** Se han dejado métodos auxiliares innecesarios en la clase holaBot.

**Comment by AlbertoBujMun** [comment]
No se pueden eliminar esos métodos de ahí porque usan métodos estáticos de la clase AbilityBot. De momento, al ser métodos privados simples, creo que están bien ahí.
