### ISSUE TITLE
Falta contenido en la Wiki y en Readme.md

### ISSUE THREAD

**Issue by Jultrocor** [EGC-G2-Trabajo-1718/Cabina-Telegram#3]
Prioridad: Alta
Descripción: Completar el formato de los issues y los commits y demás información.

**Comment by AlbertoBujMun** [comment]
He actualizado los contenidos de la wiki. Aseguraos de seguir el formato de commits que aparece en la wiki de integración, ya que me parecía una tontería copiar el mismo texto de un lado a otro.
