### ISSUE TITLE
Función de prueba /login no cambiada

### ISSUE THREAD

**Issue by daniglper** [EGC-G2-Trabajo-1718/Cabina-Telegram#4]
Prioriad: Media
Descripción: La función /login sigue en una versión de prueba en la que te pide el nombre y el apellido y te da una respuesta. Debería de pedir los credenciales para autenticarte en lugar de esta versión de prueba.

**Comment by vicrosa25** [comment]
Esperando que nos faciliten los datos de los usuarios.
