### ISSUE TITLE
Obtener usuarios para la función Login

### ISSUE THREAD

**Issue by vicrosa25** [EGC-G2-Trabajo-1718/Cabina-Telegram#7]
Faltan los datos de los usuarios (username, password) para poder realizar la función login.

**Comment by AlbertoBujMun** [comment]
Este issue correspondría escribirlo al equipo de autenticación. Me pongo en contacto con ellos e investigo a ver como llevan de avanzada su API pero hasta que no se produzca integración no podremos probar los datos.
