### ISSUE TITLE
Falta la funcionalidad comprobarPregunta.

### ISSUE THREAD

**Issue by alegamdev** [EGC-G2-Trabajo-1718/Cabina-Telegram#9]
**Prioridad**: Media.
**Descripción**: Falta la funcionalidad comprobarPregunta en la clase votarFunctionality que compruebe la existencia de una pregunta de una **votación existente** en el sistema.

**Comment by Jultrocor** [comment]
La funcionalidad prevista del sistema hace que el método votar devuelva las preguntas de la votación elegida, por tanto no es necesario realizar esa comprobación.
